repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false

      # - id: cargo-clippy
      #   name: cargo clippy
      #   entry: cargo clippy
      #   language: system
      #   args: ["--", "-D", "warnings"]
      #   types: [rust]
      #   pass_filenames: false
